# Generated by Django 4.1.5 on 2023-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='bootstrap', max_length=255),
            preserve_default=False,
        ),
    ]
