# Generated by Django 4.1.5 on 2023-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_content',
            field=models.CharField(default='Bootstrap utilizes Sass for a modular and customizable architecture. Import only the components you need, enable global options like gradients and shadows, and write your own CSS with our variables, maps, functions, and mixins.', max_length=250),
            preserve_default=False,
        ),
    ]
