# Generated by Django 4.1.5 on 2023-01-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
